version: '3.2'
services:
  web:
    image: nginx
    depends_on:
      - reactapp
      - node
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - NODE_PORT=${NODE_PORT}
    volumes:
      - ./site.dev.conf:/etc/nginx/conf.d/site.template:ro
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
  node:
    image: node:latest
    environment:
      - NODE_PORT=${NODE_PORT}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - database
    working_dir: /var/www/node
    volumes:
      - ./server/:/var/www/node
      - /var/www/node/node_modules
    command: bash -c "yarn install && yarn start"
  database:
    image: mongo:latest
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
       - ./database:/data/db
  reactapp:
    image: node:latest
    environment:
      - PORT=${FRONTEND_PORT}
      - NODE_PATH=${NODE_PATH}
    working_dir: /home/app
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules
    command: bash -c "yarn install && yarn start"
